app: mpv
binpatch: true

ingredients:
  dist: stable
  package: mpv
  sources:
    - deb http://www.deb-multimedia.org stable-backports main non-free 
    - deb http://www.deb-multimedia.org stable main non-free
    - deb http://ftp.debian.org/debian/ stable main contrib non-free non-free-firmware
    - deb http://security.debian.org/debian-security/ stable-security main contrib non-free non-free-firmware
    - deb http://ftp.debian.org/debian/ stable-updates main contrib non-free non-free-firmware
  packages:
    - mpv
    - libdavs2

script:
  - mv ./usr/lib/x86_64-linux-gnu/samba/*.so* ./usr/lib/x86_64-linux-gnu/
  - sed -i -e 's|TargetEnvironment|X-TargetEnvironment|g' mpv.desktop
  - sed -i 's|^Exec=.*|Exec=mpv |' mpv.desktop

